// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentFieldNames          = builder.RawFieldNames(&Payment{})
	paymentRows                = strings.Join(paymentFieldNames, ",")
	paymentRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	paymentRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheStarbucksPaymentIdPrefix    = "cache:starbucks:payment:id:"
	cacheStarbucksPaymentPayIdPrefix = "cache:starbucks:payment:payId:"
)

type (
	paymentModel interface {
		Insert(ctx context.Context, data *Payment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Payment, error)
		FindOneByPayId(ctx context.Context, payId string) (*Payment, error)
		Update(ctx context.Context, data *Payment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPaymentModel struct {
		sqlc.CachedConn
		table string
	}

	Payment struct {
		Id          int64     `db:"id"`
		PayId       string    `db:"pay_id"`
		UserId      string    `db:"user_id"`
		OrderId     string    `db:"order_id"`
		PayedAmount int64     `db:"payed_amount"` // 已支付金额，单位：分
		PayedTime   time.Time `db:"payed_time"`   // 支付时间
	}
)

func newPaymentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPaymentModel {
	return &defaultPaymentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`payment`",
	}
}

func (m *defaultPaymentModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	starbucksPaymentIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentIdPrefix, id)
	starbucksPaymentPayIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentPayIdPrefix, data.PayId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, starbucksPaymentIdKey, starbucksPaymentPayIdKey)
	return err
}

func (m *defaultPaymentModel) FindOne(ctx context.Context, id int64) (*Payment, error) {
	starbucksPaymentIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentIdPrefix, id)
	var resp Payment
	err := m.QueryRowCtx(ctx, &resp, starbucksPaymentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentModel) FindOneByPayId(ctx context.Context, payId string) (*Payment, error) {
	starbucksPaymentPayIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentPayIdPrefix, payId)
	var resp Payment
	err := m.QueryRowIndexCtx(ctx, &resp, starbucksPaymentPayIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `pay_id` = ? limit 1", paymentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, payId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentModel) Insert(ctx context.Context, data *Payment) (sql.Result, error) {
	starbucksPaymentIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentIdPrefix, data.Id)
	starbucksPaymentPayIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentPayIdPrefix, data.PayId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, paymentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PayId, data.UserId, data.OrderId, data.PayedAmount, data.PayedTime)
	}, starbucksPaymentIdKey, starbucksPaymentPayIdKey)
	return ret, err
}

func (m *defaultPaymentModel) Update(ctx context.Context, newData *Payment) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	starbucksPaymentIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentIdPrefix, data.Id)
	starbucksPaymentPayIdKey := fmt.Sprintf("%s%v", cacheStarbucksPaymentPayIdPrefix, data.PayId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PayId, newData.UserId, newData.OrderId, newData.PayedAmount, newData.PayedTime, newData.Id)
	}, starbucksPaymentIdKey, starbucksPaymentPayIdKey)
	return err
}

func (m *defaultPaymentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheStarbucksPaymentIdPrefix, primary)
}

func (m *defaultPaymentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPaymentModel) tableName() string {
	return m.table
}
